package cli

const (
	tcTargetA      = "a.go"
	tcTargetB      = "b.go"
	tcTargetC      = "c.go"
	tcCmdLock      = "lock"
	tcCmdUnlock    = "unlock"
	tcCmdStatus    = "status"
	tcCmdCheck     = "check"
	tcCmdDoctor    = "doctor"
	tcTargetX      = "x.go"
	tcFlagRepair   = "--repair"
	tcFlagOrphan   = "--orphan-mode"
	tcFlagMine     = "--mine"
	tcFlagIntent   = "--intent"
	tcFlagTTL      = "--ttl"
	tcSlugDKLoto   = "dkoosis-loto"
	tcStoreStoreGo = "internal/store/store.go"
	tcIntentTest   = "test"
	tcIntentDone   = "done"
	tcIntentWrite  = "write"
	tcIntentRead   = "read"
	tcCmdTag       = "tag"
	tcCmdAck       = "ack"
	tcCmdDowngrade = "downgrade"
	tcCmdRefresh   = "refresh"
	tcFlagAll      = "--all"
	tcFlagShared   = "--shared"
	tcCmdLane      = "lane"
	tcCmdVerify    = "verify"
	tcShExit0      = "exit 0" // the no-op verify command, as `sh -c` takes it
	tcFlagRef      = "--ref"
	tcFlagBase     = "--base"
	tcFlagCloses   = "--closes"
	tcMsg          = "msg"
	tcHEAD         = "HEAD"
	tcClosesNone   = "none"
	tcRefImpl1     = "impl-1"
	tcClosesAbc    = "loto-abc"
	tcTargetSym    = "sym.go"
	tcStoreGo      = "store.go"
	tcFlagForce    = "--force"
	// tcHoldAlice1 is a well-formed but deliberately WRONG --expect-holder
	// token: the parse must succeed so the compare, not the parser, does the
	// refusing.
	tcHoldAlice1 = "alice@1"
)
