package cli

const (
	tcTargetA      = "a.go"
	tcTargetB      = "b.go"
	tcTargetC      = "c.go"
	tcCmdLock      = "lock"
	tcCmdUnlock    = "unlock"
	tcCmdStatus    = "status"
	tcCmdCheck     = "check"
	tcCmdDoctor    = "doctor"
	tcTargetX      = "x.go"
	tcFlagRepair   = "--repair"
	tcFlagOrphan   = "--orphan-mode"
	tcFlagMine     = "--mine"
	tcFlagIntent   = "--intent"
	tcFlagTTL      = "--ttl"
	tcSlugDKLoto   = "dkoosis-loto"
	tcStoreStoreGo = "internal/store/store.go"
	tcIntentTest   = "test"
	tcIntentDone   = "done"
	tcIntentWrite  = "write"
	tcIntentRead   = "read"
	tcCmdTag       = "tag"
	tcCmdAck       = "ack"
	tcCmdDowngrade = "downgrade"
	tcFlagAll      = "--all"
	tcFlagShared   = "--shared"
)
